apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    team: devops
    version: "1.0"
    status: learn-kubernetes 
  annotations:
    description: learn kubernetes with docker desktop
    images: image contains a simple web template using html and css
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
        department: devops
    spec:
       containers:
        - name: httpd
          image: "naldostev/testweb:1.2"
          ports:
            - containerPort: 80
   
---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
    department: devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001